# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish ContosoMasks.com/ContosoMasks.com.sln --configuration $(buildConfiguration) -o publish 
  displayName: 'dotnet publish $(buildConfiguration)'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'publish' 
    includeRootFolder: false
    archiveType: 'zip'    
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Azure Internal Consumption (andywahr)(84bcbb63-5ce7-47d6-9481-0ddd39d8d250)'
    appType: 'webApp'
    WebAppName: 'contosomasks'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

